version: "3"
services:
  tcgdex:
    volumes:
      - ../:/home/tcgdex
    command: "yarn dev"
    tty: true
    ports:
      - "3000:3000"
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - 8081:80
      networks:
          - network
      env_file:
          - .env
          - .env.local
